### ISSUE TITLE
get-remnux.sh remnux-scripts / remnux-oletools hanging

### ISSUE THREAD

**Issue by Mooey28** [REMnux/distro#10]
Running the get-remnux.sh script to install REMnux on SIFT. It is reaching the "Installing APT Package: remnux-scripts" step then hanging. Checking the log, it appears to be stuck at the following. My get reached over 15,000 earlier before I retried:

_Get:656 http://ppa.launchpad.net/remnux/stable/ubuntu/ trusty/main remnux-oletools amd64 0.51a-2 [749 kB]_

Is there any issue with this?

**Comment by Djent-** [comment]
I had a similar hang. I don't know what log you found that in though. My /var/log/apt/history.log only had python common
