### ISSUE TITLE
OVA Does Not Import with ESXi 6.5

### ISSUE THREAD

**Issue by clairmont32** [REMnux/distro#15]
Hello,

Unfortunately, there was no real helpful error message from my ESXi environment (only `unknown error`). I know this isn't very helpful information but here's the (default) process I was following:

- Create/Register VM
- Deploy a virtual machine from an OVF or OVA file
- Name and select the OVA
- Set NIC and Thin provision
- Finish

Client version:
1.23.0
Client build number:
6506686
ESXi version:
6.5.0
ESXi build number:
7388607

Please let me know if there's anything I can do to assist in troubleshooting or resolving the issue.

**Comment by lennyzeltser** [comment]
Without additional details, I'm not sure how I can assist. If importing the OVA isn't working for you, consider following the alternative installation process, where you start with a minimal Ubuntu 14.04 VM that you're imported into ESXi, and use the REMnux installer script to build the VM from that point.
