### ISSUE TITLE
Proposal for additional Debian packages

### ISSUE THREAD

**Issue by KurtPfeifle** [REMnux/distro#2]
I want to propose the addition of the following .deb packages to REMnux:
- `unicode`
- `scli` (SNMP Command Line Interface)
- `qpdf`
- `pdfresurrect`
- `lcdf-typetools`
- `fonttools`
- `libpodofo-utils`

(If you need to hear arguments about each of the above, let me know.)

**Comment by lennyzeltser** [comment]
I've added unicode, qpdf and pdfresurrect to the REMnux installation/upgrade script, per your suggestions. I am not sure the other 4 tools you mentioned will be very useful to the broader audience--could you expand upon your recommendations regarding these utilities?

**Comment by KurtPfeifle** [comment]
Thanks for adding these 3 for now!

About the other 4 ones:

* **`scli`:** I just noticed that Debian Jessie doesn't include it any more, but I don't know the reason (yet). However, I've recently apt-gotten installed it on a fairly recent Ubuntu version.

    Here is an article I wrote about it when I had discovered it about 10 years ago: http://openprinting.blogspot.de/2007/09/my-little-bag-of-tricks-scli-snmp.html

    It's no longer actively developed, but is still very useful, because even a non-SNMP expert can find useful information about SNMP-enabled devices in his network, without first learning the ins and outs of `snmpwalk` and the like. 

    While I personally am not an ITsec guy at all, I think it could play a useful role in that field as well for anybody who's a beginner in SNMP.

    The cool thing about `scli` is that it has tab completion for all its sub-commands. So you do not need to know much about it in order to start using it.

* **`lcdf-typetools`**: Just a bunch of command line tools which can analyze various types of fonts. I have recenty learned that in the past there was malware hiding inside fonts embedded in PDFs, so I thought it may be useful for REMnux too. (How to extract font files from a PDF can be learned here: http://stackoverflow.com/a/3489099/359307 (funnily, my most "popular" SO answer).

* **`fonttools`**: Similar to above. Contains the `ttx` tool (written in Python) which dissects TTF and OTF.

* **`libpodofo-utils`**: a suite of command line tools to analyze and manipulate PDF files. Contains the following: `podofobox`, `podofocrop`, `podofoimg2pdf`, `podofoincrementalupdates`, `podofopdfinfo`, `podofouncompress`, `podofocolor`, `podofoencrypt`, `podofoimgextract`, `podofomerge`, `podofotxt2pdf             podofoxmp`, `podofocountpages`, `podofogc`, `podofoimpose`, `podofopages` and `podofotxtextract`.

    These cover a similar range as the Poppler utils (`pdfinfo`, `pdfimages`, `pdfdetach`, `pdffonts`, `pdftotext` etc.), but not exactly.

    It is my experience that one tool sometimes may just die when trying to parse a weird PDF document, while the other one still extracts useful info from it. Hence my recommendation for the Podofo utils on top of the Poppler ones...
