### ISSUE TITLE
Viper - deleting a note deletes the associated file

### ISSUE THREAD

**Issue by Yawney** [REMnux/distro#3]
There is an issue with Viper. If a note is deleted it also deletes the associated file.
It is documented here: https://github.com/viper-framework/viper/issues/316.
It was fixed in https://github.com/viper-framework/viper/commit/4e8cf8e5b6b2138cca6dc0377bc582a943f2d37e.

Would it be possible to include a newer version of Viper in REMnux so that others won't run into this issue?

**Comment by lennyzeltser** [comment]
Done. Thanks for the recommendation.

To get the latest version of the Viper package, please run the `update-remnux` command, which will also address some of the new dependencies. You need to run this version from the /opt/remnux-viper directory, where you'll find viper.py and web.py scripts.

If you notice any issues with the updated package, please let me know.

Also, I updated the Docker image of Viper "remnux/viper" in the REMnux repository, which you can run according to [these instructions](https://remnux.org/docs/containers/run-apps/#viper-binary-analysis-framework-remnuxviper).
