### ISSUE TITLE
Remnux update seems to break Volatility 2.5

### ISSUE THREAD

**Issue by ottoscav** [REMnux/distro#4]
Volatility works just fine prior to updating Remnux with the update-remnux command. Afterwards, when Volatility 2.5 is installed, it's broken. Suggestions?

![image](https://cloud.githubusercontent.com/assets/8440770/13436438/43f4c7ae-dfad-11e5-8c67-47d844cc39df.png)

**Comment by lennyzeltser** [comment]
I think the issue is the compatibility of the older EditBox plugin. Could you try removing the following file(s) to see whether this corrects the problem?

/usr/lib/python2.7/dist-packages/volatility/plugins/editbox.py*

**Comment by beast-fighter** [comment]
@ottoscav I looked into this earlier today. @lennyzeltser is right, the issue exists with editbox.
To resolve this issue, run the following command:
`sudo rm /usr/lib/python2.7/dist-packages/volatility/plugins/gui/editbox.py* && sudo rm /usr/lib/python2.7/dist-packages/volatility/plugins/editbox.py`

Please let us know if you run into any further issues.

Thanks,

**Comment by ottoscav** [comment]
Worked great, thanks to you both!

**Comment by lennyzeltser** [comment]
I've now updated the remnux-volatility-plugins to address this issue automatically, so that people won't encounter the problem after updating REMnux.
