### ISSUE TITLE
Download in .iso format missing

### ISSUE THREAD

**Issue by nouser1104** [REMnux/distro#5]
Maybe not a real issue, I just don't know where else I should ask this question...
According to your website the easiest way to get  REMnux is to "download the REMnux virtual appliance file". My problem is that I need an .iso file because I want to copy the OS on a USB-Stick and carry it around with me so I can use it on real systems, not just virtual machines. Neither on the website nor on [Sourceforge](https://sourceforge.net/projects/remnux/) is any information about how to get it, while there are .iso files until REMnux v5. If there is an v6 ISO, could you please make a note on your website about where to find it?
Thank you

**Comment by lennyzeltser** [comment]
Starting with version 6, REMnux is no longer available as an ISO file, sorry.
