### ISSUE TITLE
SIFT+Remnux pytsk3 issues

### ISSUE THREAD

**Issue by DigiAngel** [REMnux/distro#9]
Leaving this here...I have several machines with SIFT+Remnux, now it looks like these two are conflicting here:

```
https://github.com/sans-dfir/sift/issues/110#issuecomment-250238600
```

In a nutshell:

```
Preparing to unpack .../python-pytsk3_20160721-1ppa1~trusty_amd64.deb ...
Unpacking python-pytsk3 (20160721-1ppa1~trusty) ...
dpkg: error processing archive /var/cache/apt/archives/python-pytsk3_20160721-1ppa1~trusty_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/python2.7/dist-packages/pytsk3.so', which is also in package pytsk3 4.2.0-20150406-1ppa1~trusty
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```

Is there a fix I can use to resurrect these machines?  Thank you.

**Comment by arrigo** [comment]
You might want to have a look at https://github.com/sans-dfir/sift/issues/110#issuecomment-285231089 where I posted a solution for _mantaray_.

If you do not need _mantaray_ then you need to clean up your packages as explained in a linked issue.
